replicaCount: 1

image:
  repository: ghcr.io/vikranth18devops
  pullPolicy: IfNotPresent
  frontendTag: "05bd9ae9cffbc803116ca4faf6b7893d6f2869ea"
  backendTag: "05bd9ae9cffbc803116ca4faf6b7893d6f2869ea"
  uiScriptTag: "05bd9ae9cffbc803116ca4faf6b7893d6f2869ea"

service:
  frontendPort: 80
  backendPort: 8000
  uiScriptPort: 8585

# In-Cluster Kubernetes PostgreSQL StatefulSet Configuration
postgres:
  enabled: true
  user: "finopsadmin"
  password: "SecretPass123!"
  database: "cloud_cost_db"
  storageSize: "10Gi"

resources:
  frontend:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
  backend:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  uiScript:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# HorizontalPodAutoscaler (HPA v2) Configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 80

env:
  # In-cluster Kubernetes PostgreSQL connection string
  DATABASE_URL: "postgresql://finopsadmin:SecretPass123!@postgres-service.finops.svc.cluster.local:5432/cloud_cost_db"
  JWT_SECRET: "super_secure_jwt_secret_key_2026"
  AZURE_SUBSCRIPTION_ID: "afa17bb6-6630-4872-8141-2a62d46e3053"
